name: Build and Package Psych Engine

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Haxe
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.3.4

    - name: Install Ubuntu Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libalut-dev libasound2-dev libx11-dev libxext-dev libxi-dev librandr-dev libxinerama-dev libxcursor-dev libvlc-dev libvlccore-dev

    - name: Install Haxelibs
      run: |
        haxelib setup ~/haxelib
        haxelib install lime
        haxelib install openfl
        haxelib install flixel
        haxelib run lime setup

    - name: Compile Game
      run: |
        haxelib run lime build linux -release

    - name: Zip Psych Engine Release
      run: |
        cd game_folder/PsychEngine
        zip -r ../../psych-engine-release.zip ./*

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PsychEngine-Linux-Build
        path: psych-engine-release.zip
