name: Upload APK to Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Download File
        run: |
          python -c "
          import requests

          target_url = 'https://download2447.mediafire.com/m09epp5b9hcgcCRbSyyTA0IeJWOE07PD8jHMB0RXoTQ-QzWhcTxRrNbz1k7cBspYNzr9iH2uJD0N5r75HVwhXblUThuVcpX8txq9QGTfNloUJuWwyVo9bN_cH_8Apmkh3PRW5lU6duVQFegvegBg2TMEs9q1-nhIVdShXIglhAMU/cvebskc7c9yee3e/Dead-Cells-v3.5.9-unlocked.apk'
          headers = {
              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'
          }

          with requests.get(target_url, stream=True, headers=headers, allow_redirects=True) as r:
              r.raise_for_status()
              with open('Dead_Cells_v3.5.9_unlocked.apk', 'wb') as f:
                  for chunk in r.iter_content(chunk_size=8192):
                      if chunk:
                          f.write(chunk)
          "

      - name: Verify Size
        run: |
          FILE_SIZE=$(stat -c%s "Dead_Cells_v3.5.9_unlocked.apk")
          if [ $FILE_SIZE -lt 1000000 ]; then
            echo "File size too small, download might have failed."
            exit 1
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v2.52.3-beta
          name: "Dead Cells v3.5.9 unlocked"
          body: "Automated upload of the APK file."
          draft: false
          prerelease: true
          files: Dead_Cells_v3.5.9_unlocked.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
